#!/usr/bin/env bash
# displaying "Best School" 10 times using while and if

num=1
while [ $num -le 10 ]
do
	if [ $num -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	num=$((num+1))
done
