#!/usr/bin/env bash
# loops from 1 to 10 displays bad luck in 4th iteration
# good luck for the 8th iteration
# Best School for the rest

num=1
while [ $num -le 10 ]
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	num=$((num+1))
done
